config/routes.rb
StreamingTest::Application.routes.draw do

  

  root 'messaging#index'
  get 'messaging' => 'messaging#send_message', :as => 'messaging'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messaging_controller.rb
require 'server_side/sse'

class MessagingController < ApplicationController
	include ActionController::Live

	def index
	end

	def send_message
		response.headers['Content-Type'] = 'text/event-stream'
		sse = ServerSide::SSE.new(response.stream)
		begin
			loop do
				sse.write({ :message => "#{params[:message]}" })
				sleep 1
			end
		rescue IOError
		ensure
			sse.close
		end
	end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
	def index
		@users = User.all
		@tickets = Ticket.all
		@attachments = Attachment.all

		render stream: true
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messaging_helper.rb
module MessagingHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StreamingTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/messaging/index.erb
<%= form_tag messaging_path, :method => 'get' do %>

<%= text_field_tag :message, params[:message] %>
<%= submit_tag "Post Message" %>
<script type="text/javascript">
	var source = new EventSource('/messaging?message="awesome"');
	source.addEventListener('message', function(e) {
		console.log(e.data);
	}, false);

	source.addEventListener('open', function(e) {
	  // Connection was opened.
	}, false);

	source.addEventListener('error', function(e) {
		if (e.readyState == EventSource.CLOSED) {
	    // Connection was closed.
	  }
	}, false);
</script>

<% end %>